name: Deploy to github page
on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  flutter-version: "3.24.x"
            - name: Deploy flutter web
              run: |
                  flutter pub get
                  flutter build web --release \
                    --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
                    --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            - name: deploy to github pages
              uses: eaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build/web
                  cname: vahid-rajabi.sbs
